export const ROUTES = {
  NOT_FOUND: '*',
  ROOT: '/',
  READER: '/',
  DASHBOARD: '/dashboard',
  SYLLABUS: '/syllabus',
  SYLLABUS_DETAIL: '/syllabus/:paperId',
  STUDY: '/study',
  PROBLEMS: '/problems',
  PROGRESS: '/progress',
  SETTINGS: '/settings',
  UNAUTHORIZED: '/unauthorized',
  FORM_COMPONENTS_DEMO: '/form-components-demo',
  TABLE_DEMO: '/table-demo',
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    VERIFY: '/auth/verify',
  },
  USER: {
    DASHBOARD: '/user/dashboard',
  },
}
